---
title: Lopreiato.Family
baseurl: /lopreiato.family
url: https://dlopreiato.github.io
timezone: America/New_York
collections:
  profiles:
    title: Profiles
    output: true
    permalink: "/:path/"
defaults:
- scope:
    path: ''
    type: profiles
  values:
    layout: profile
