---
title: Lopreiato.Family
baseurl: dlopreiato.github.io/lopreiato.family/
timezone: America/New_York
collections:
  profiles:
    title: Profiles
    output: true
    permalink: "/:path/"
defaults:
- scope:
    path: ''
    type: profiles
  values:
    layout: profile
